# Generated by Django 4.2 on 2023-04-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Height', models.CharField(max_length=200)),
                ('Weight', models.CharField(max_length=200)),
            ],
        ),
    ]
